In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
import pandas as pd
import numpy as np
import json
import pprint
import urllib.request
from collections import Counter

In [4]:
## Read in all of the data and convert appropriate columns to a "Date" data type

df = pd.read_csv('ss.csv')

In [6]:
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

In [7]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [8]:
# convert the 'Date' column to datetime format
df['Order Date']= pd.to_datetime(df['Order Date'])
df['Ship Date']= pd.to_datetime(df['Ship Date'])

In [9]:
# Check the format of 'Date' column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [10]:
## View the first few rows. Show the data type for all columns, as well as the number of rows and columns

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

In [11]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [13]:
df.shape

(9994, 21)

In [15]:
# Set the column ''Row ID" as the index column. Make sure to check if the column values are unique

df = df.set_index('Row ID')
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.25,3,0.20,4.10
9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,15.63
9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39
9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32
9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.95

In [20]:
df["Ship Mode"].unique

<bound method Series.unique of Row ID
1         Second Class
2         Second Class
3         Second Class
4       Standard Class
5       Standard Class
             ...
9990      Second Class
9991    Standard Class
9992    Standard Class
9993    Standard Class
9994      Second Class
Name: Ship Mode, Length: 9994, dtype: object>

In [21]:
df["Segment"].unique

<bound method Series.unique of Row ID
1        Consumer
2        Consumer
3       Corporate
4        Consumer
5        Consumer
          ...
9990     Consumer
9991     Consumer
9992     Consumer
9993     Consumer
9994     Consumer
Name: Segment, Length: 9994, dtype: object>

In [22]:
# Show the data types and non-null value counts for all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9994 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   datetime64[ns]
 2   Ship Date      9994 non-null   datetime64[ns]
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   Country        9994 non-null   object
 8   City           9994 non-null   object
 9   State          9994 non-null   object
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   object
 12  Product ID     9994 non-null   object
 13  Category       9994 non-null   object
 14  Sub-Category   9994 non-null   object
 15  Product Name   9994 non-null   object
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(13)
memory usage: 1.6+ MB

In [ ]:
# Convert all columns with object data type to category data type

In [24]:
df[[ 'Customer Name', 'Country', 'City', 'Product ID', 'Category', 'Sub-Category', 'Product Name']]. apply(lambda x: x. astype('category'))

,Customer Name,Country,City,Product ID,Category,Sub-Category,Product Name
Row ID,,,,,,,
1,Claire Gute,United States,Henderson,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase
2,Claire Gute,United States,Henderson,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
3,Darrin Van Huff,United States,Los Angeles,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...
4,Sean O'Donnell,United States,Fort Lauderdale,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table
5,Sean O'Donnell,United States,Fort Lauderdale,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System
...,...,...,...,...,...,...,...
9990,Tom Boeckenhauer,United States,Miami,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle
9991,Dave Brooks,United States,Costa Mesa,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...
9992,Dave Brooks,United States,Costa Mesa,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone
9993,Dave Brooks,United States,Costa Mesa,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5"""
9994,Chris Cortes,United States,Westminster,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou..."

In [27]:
df.loc[:, df.dtypes == 'object'] = df.select_dtypes(['object']).apply(lambda x: x.astype('category'))

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9994 entries, 1 to 9994
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   category
 1   Order Date     9994 non-null   datetime64[ns]
 2   Ship Date      9994 non-null   datetime64[ns]
 3   Ship Mode      9994 non-null   category
 4   Customer ID    9994 non-null   category
 5   Customer Name  9994 non-null   category
 6   Segment        9994 non-null   category
 7   Country        9994 non-null   category
 8   City           9994 non-null   category
 9   State          9994 non-null   category
 10  Postal Code    9994 non-null   int64
 11  Region         9994 non-null   category
 12  Product ID     9994 non-null   category
 13  Category       9994 non-null   category
 14  Sub-Category   9994 non-null   category
 15  Product Name   9994 non-null   category
 16  Sales          9994 non-null   float64
 17  Quantity       9994 non-null   int64
 18  Discount       9994 non-null   float64
 19  Profit         9994 non-null   float64
dtypes: category(13), datetime64[ns](2), float64(3), int64(2)
memory usage: 1.2 MB

In [29]:
# Use the bracket operator, loc, and iloc to select a few columns. Display your selections for each
df.loc[8000: 9000]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
8000,US-2014-148194,2014-05-04,2014-05-07,First Class,BS-11365,Bill Shonely,Corporate,United States,Seattle,Washington,98105,West,OFF-AP-10000696,Office Supplies,Appliances,Holmes Odor Grabber,57.68,4,0.00,19.03
8001,US-2015-151407,2015-11-08,2015-11-12,Standard Class,RD-19585,Rob Dowd,Consumer,United States,Dubuque,Iowa,52001,Central,TEC-PH-10003885,Technology,Phones,Cisco SPA508G,263.96,4,0.00,76.55
8002,CA-2015-110870,2015-12-12,2015-12-15,First Class,KD-16270,Karen Daniels,Consumer,United States,Los Angeles,California,90032,West,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,299.94,6,0.00,128.97
8003,CA-2015-110870,2015-12-12,2015-12-15,First Class,KD-16270,Karen Daniels,Consumer,United States,Los Angeles,California,90032,West,OFF-SU-10001225,Office Supplies,Supplies,Staple remover,25.76,7,0.00,0.52
8004,CA-2014-143210,2014-12-01,2014-12-03,First Class,AA-10645,Anna Andreadi,Consumer,United States,Lowell,Massachusetts,1852,East,TEC-PH-10004434,Technology,Phones,Cisco IPï¿½Phoneï¿½7961G VoIPï¿½phoneï¿½- Dark gray,271.90,2,0.00,78.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8996,CA-2014-109043,2014-08-15,2014-08-17,First Class,CS-12355,Christine Sundaresam,Consumer,United States,Hollywood,Florida,33021,South,OFF-AP-10004708,Office Supplies,Appliances,Fellowes Superior 10 Outlet Split Surge Protector,152.24,5,0.20,17.13
8997,US-2017-116491,2017-11-11,2017-11-13,First Class,PG-18820,Patrick Gardner,Consumer,United States,Dallas,Texas,75081,Central,TEC-PH-10004531,Technology,Phones,OtterBox Commuter Series Case - iPhone 5 & 5s,35.18,2,0.20,12.31
8998,CA-2017-122763,2017-03-20,2017-03-20,Same Day,HG-14845,Harry Greene,Consumer,United States,Houston,Texas,77041,Central,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,56.70,2,0.20,19.14
8999,CA-2017-122763,2017-03-20,2017-03-20,Same Day,HG-14845,Harry Greene,Consumer,United States,Houston,Texas,77041,Central,OFF-PA-10002377,Office Supplies,Paper,Xerox 1916,274.06,7,0.20,102.77
9000,CA-2017-137785,2017-05-13,2017-05-17,Standard Class,MH-18115,Mick Hernandez,Home Office,United States,Philadelphia,Pennsylvania,19140,East,FUR-CH-10001482,Furniture,Chairs,Office Star - Mesh Screen back chair with Viny...,458.43,5,0.30,-124.43

In [30]:
df.iloc[[-5,-3,-2,-1]]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.25,3,0.20,4.10
9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39
9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.00,13.32
9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.95

In [31]:
# Select all columns with numeric data types
df.select_dtypes(include=["number"])

        Postal Code  Sales  Quantity  Discount  Profit
Row ID
1             42420 261.96         2      0.00   41.91
2             42420 731.94         3      0.00  219.58
3             90036  14.62         2      0.00    6.87
4             33311 957.58         5      0.45 -383.03
5             33311  22.37         2      0.20    2.52
...             ...    ...       ...       ...     ...
9990          33180  25.25         3      0.20    4.10
9991          92627  91.96         2      0.00   15.63
9992          92627 258.58         2      0.20   19.39
9993          92627  29.60         4      0.00   13.32
9994          92683 243.16         2      0.00   72.95

[9994 rows x 5 columns]

In [32]:
# Use slicing to start at the 1001st row and go to the 2000th row, skipping every other row
df.loc[1001: 2000]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
1001,CA-2016-155488,2016-11-13,2016-11-17,Standard Class,FM-14290,Frank Merwin,Home Office,United States,Vancouver,Washington,98661,West,OFF-AR-10002956,Office Supplies,Art,Boston 16801 Nautilus Battery Pencil Sharpener,44.02,2,0.00,11.45
1002,CA-2015-124891,2015-07-31,2015-07-31,Same Day,RH-19495,Rick Hansen,Consumer,United States,New York City,New York,10024,East,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,"2,309.65",7,0.00,762.18
1003,CA-2015-124891,2015-07-31,2015-07-31,Same Day,RH-19495,Rick Hansen,Consumer,United States,New York City,New York,10024,East,FUR-TA-10002903,Furniture,Tables,"Bevis Round Bullnose 29"" High Table Top","1,090.78",7,0.40,-290.88
1004,CA-2015-124891,2015-07-31,2015-07-31,Same Day,RH-19495,Rick Hansen,Consumer,United States,New York City,New York,10024,East,OFF-PA-10004621,Office Supplies,Paper,Xerox 212,19.44,3,0.00,9.33
1005,CA-2015-126445,2015-08-27,2015-08-31,Standard Class,RA-19945,Ryan Akin,Consumer,United States,Murrieta,California,92563,West,OFF-ST-10000046,Office Supplies,Storage,Fellowes Super Stor/Drawer Files,484.65,3,0.00,92.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,US-2017-147221,2017-12-02,2017-12-04,Second Class,JS-16030,Joy Smith,Consumer,United States,Houston,Texas,77036,Central,OFF-AP-10002534,Office Supplies,Appliances,3.6 Cubic Foot Counter Height Office Refrigerator,294.62,5,0.80,-766.01
1997,US-2017-147221,2017-12-02,2017-12-04,Second Class,JS-16030,Joy Smith,Consumer,United States,Houston,Texas,77036,Central,FUR-FU-10004020,Furniture,Furnishings,Advantus Panel Wall Acrylic Frame,8.75,4,0.60,-3.72
1998,CA-2014-131905,2014-02-06,2014-02-09,First Class,ND-18460,Neil Ducich,Corporate,United States,Chesapeake,Virginia,23320,South,OFF-LA-10002787,Office Supplies,Labels,Avery 480,15.00,4,0.00,7.20
1999,CA-2014-131905,2014-02-06,2014-02-09,First Class,ND-18460,Neil Ducich,Corporate,United States,Chesapeake,Virginia,23320,South,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,161.61,1,0.00,42.02
2000,CA-2014-131905,2014-02-06,2014-02-09,First Class,ND-18460,Neil Ducich,Corporate,United States,Chesapeake,Virginia,23320,South,TEC-PH-10001615,Technology,Phones,AT&T CL82213,144.95,5,0.00,42.04

In [37]:
# Select all the rows where 'Sales' exceed $100

sales = df.loc[(df.Sales>100)]
sales

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.15,6,0.20,90.72
10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.90,5,0.00,34.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.58,2,0.20,31.20
9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,California,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.47,14,0.20,153.12
9989,CA-2017-163629,2017-11-17,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,Georgia,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.10,5,0.00,55.65
9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.58,2,0.20,19.39
9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.95

In [41]:
# Select al rows dealing with 'office supplies' where 'Profit' is negative (i.e., there is loss)

Negative_offsupplies = df.loc[(df.Category == 'Office Supplies') & (df.Profit<0)]
Negative_offsupplies

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Row ID,,,,,,,,,,,,,,,,,,,,
15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.81,5,0.80,-123.86
16,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.54,3,0.80,-3.82
29,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.62,2,0.70,-7.05
33,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140,East,OFF-BI-10001525,Office Supplies,Binders,"Acco Pressboard Covers with Storage Hooks, 14 ...",6.86,6,0.70,-5.71
75,US-2015-134026,2015-04-26,2015-05-02,Standard Class,JE-15745,Joel Eaton,Consumer,United States,Memphis,Tennessee,38109,South,OFF-ST-10004123,Office Supplies,Storage,Safco Industrial Wire Shelving System,72.78,1,0.20,-18.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9871,CA-2014-114195,2014-11-01,2014-11-03,First Class,EA-14035,Erin Ashbrook,Corporate,United States,Mason,Ohio,45040,East,OFF-BI-10001658,Office Supplies,Binders,GBC Standard Therm-A-Bind Covers,22.43,3,0.70,-17.94
9877,US-2017-166324,2017-04-20,2017-04-21,First Class,BE-11455,Brad Eason,Home Office,United States,Cleveland,Ohio,44105,East,OFF-ST-10000078,Office Supplies,Storage,Tennsco 6- and 18-Compartment Lockers,848.54,4,0.20,-21.21
9878,US-2017-166324,2017-04-20,2017-04-21,First Class,BE-11455,Brad Eason,Home Office,United States,Cleveland,Ohio,44105,East,OFF-BI-10000174,Office Supplies,Binders,Wilson Jones Clip & Carry Folder Binder Tool f...,8.70,5,0.70,-6.38
9921,CA-2016-149272,2016-03-15,2016-03-19,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,Texas,77803,Central,OFF-BI-10004233,Office Supplies,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.39,7,0.80,-35.82
9922,CA-2014-111360,2014-11-24,2014-11-30,Standard Class,AT-10435,Alyssa Tate,Home Office,United States,Akron,Ohio,44312,East,OFF-BI-10003350,Office Supplies,Binders,Acco Expandable Hanging Binders,5.74,3,0.70,-4.59

In [42]:
# Show the frequencies and percentages for columns 'Quantity' and 'Discount'

df.Quantity.value_counts()

3     2409
2     2402
5     1230
4     1191
1      899
7      606
6      572
9      258
8      257
10      57
11      34
14      29
13      27
12      23
Name: Quantity, dtype: int64

In [43]:
df.Quantity.value_counts(normalize=True)

3    0.24
2    0.24
5    0.12
4    0.12
1    0.09
7    0.06
6    0.06
9    0.03
8    0.03
10   0.01
11   0.00
14   0.00
13   0.00
12   0.00
Name: Quantity, dtype: float64

In [44]:
df.Discount.value_counts()

0.00    4798
0.20    3657
0.70     418
0.80     300
0.30     227
0.40     206
0.60     138
0.10      94
0.50      66
0.15      52
0.32      27
0.45      11
Name: Discount, dtype: int64

In [45]:
df.Quantity.value_counts(normalize=True)

3    0.24
2    0.24
5    0.12
4    0.12
1    0.09
7    0.06
6    0.06
9    0.03
8    0.03
10   0.01
11   0.00
14   0.00
13   0.00
12   0.00
Name: Quantity, dtype: float64

In [47]:
#Show the distribution of values for the 'Sales' and 'Discount' columns

df.Quantity.describe().T

count   9,994.00
mean        3.79
std         2.23
min         1.00
25%         2.00
50%         3.00
75%         5.00
max        14.00
Name: Quantity, dtype: float64

In [48]:
df.Discount.describe().T

count   9,994.00
mean        0.16
std         0.21
min         0.00
25%         0.00
50%         0.20
75%         0.20
max         0.80
Name: Discount, dtype: float64